---
title: 'Lab-3'
author: "Dr. Purna Gamage"
format: 
  html: 
    embed-resources: true
---

# Problem 1:

Plot probability density histograms for these discrete distributions (hint: use the d...() function).

a. Binomial Distribution

```
x <- 0:50
plot(x,dbinom(x,size=50,prob=.33),type="h")
```

b. Discrete uniform

```
library("extraDistr")
```

c. Bernoulli

d. Poisson

e. Geometric

f. Hyper-geometric

g. Negative binomial


# Problem 2.

Suppose there are fifteen multiple choice questions in `DSAN-5100` midterm test. Each question has four possible answers, and only one of them is correct. Find the probability of having four or less correct answers if a student attempts to answer every question at random.

a. Compute the probability of having exactly 4 correct answers by random attempts using _dbinom()_ and _pbinom()_.

b. Find the the probability of having four or less correct answers by random attempts using _dbinom()_.

c. Compute the above probability(part-b) using _pbinom()_.


# Problem 3:

`use r to find the probability`

a. Assume an insurance company receives 3 motor vehicle insurance claims per week. What is the probability that they recieve 11 or fewer claims during a month?

$$P(X\le11)?$$


b. While you are at the Georgetown library terrace, you notice that airplanes fly at an average rate of 1 every 4 hours. What is the probability that you will see at least one plane in the next hour?

# Problem 4: 

`Try this example with _..nbinom()_`

(This relates to Problem-1 in Lab-1 Assignment)

Mike had the first three successes in trials 6, 8, and 9. He had six failures until he reached three successes.

Do you think Mike has _success probability p = 0.5 or better?_
Can a simulation give an answer?Let's try.

1.  If Mike’s success probability is p = 0.5 What is the probability that he will obtain these 3 successes?. 

2. Run many simulations (say 10,000) with this success probability to find the same probability $P(X=6)?$ _Hint: Use rnbinom()_

3. If Mike’s success probability were 0.5 or better, he would not need a lot of attempts.
Find the probability that three successes were reached after 9 tosses or later by somebody with success probability 0.5. $P(X\ge6)$

a. Calculate the probabiliy using both _dnbinom()_ and _pnbinom()_.

b. Calculate this probability using a Simulation(10,000)

c. Is this probability (part b) the same as you got from "myattempts": Lab 1 Assignment Problem 1 part 3?
